# Generated by Django 4.2.16 on 2024-10-17 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('user', 'competition'), ('user', 'holicompetition')},
        ),
    ]
