# Generated by Django 5.0.3 on 2024-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_mpesatransaction_merchant_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='result_desc',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
