# Generated by Django 4.2.16 on 2024-10-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
