# Generated by Django 4.2.16 on 2024-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_model', models.CharField(max_length=100)),
                ('holiday_brand', models.CharField(default='one', max_length=100)),
                ('description', models.TextField()),
                ('specifications', models.TextField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tickets', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('max_entries_per_user', models.PositiveIntegerField()),
                ('tickets_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
