# Generated by Django 4.2.16 on 2024-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_rename_holiday_brand_holidaycompetition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaycompetition',
            name='name',
            field=models.CharField(default='diani', max_length=100),
        ),
    ]
