# Generated by Django 4.2.16 on 2024-10-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_alter_holidaycompetition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rules',
        ),
    ]
