# Generated by Django 4.2.16 on 2024-10-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0015_remove_competition_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaycompetition',
            name='specifications',
        ),
    ]
