# Generated by Django 4.2.16 on 2024-10-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_remove_holidaycompetition_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoliCompetitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='competition.holidaycompetition')),
            ],
        ),
    ]
