# Generated by Django 4.2.16 on 2024-10-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_holicompetitionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='added_date',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='holicompetition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.holidaycompetition'),
        ),
    ]
