# Generated by Django 4.2.16 on 2024-10-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_remove_basketitem_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
    ]
