# Generated by Django 4.2.16 on 2024-10-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_alter_basketitem_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='competition',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='holicompetition',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='competition.holidaycompetition'),
            preserve_default=False,
        ),
    ]
