# Generated by Django 4.2.16 on 2024-10-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0020_alter_basketitem_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='holicompetition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='competition.holidaycompetition'),
        ),
    ]
