# Generated by Django 4.2.16 on 2024-10-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0021_alter_basketitem_holicompetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='holicompetition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.holidaycompetition'),
        ),
    ]
