# Generated by Django 4.2.16 on 2024-10-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_alter_basketitem_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.holidaycompetition'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
    ]
