# Generated by Django 4.2.16 on 2024-10-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0023_winner_holiday_alter_winner_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competition.holidaycompetition'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.holidaycompetition'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competition.competition'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.competition'),
        ),
    ]
